#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May  2 22:57:38 2023

@author: caitlin
"""

def handle_theta_angle(input_angle):
    print(int(input_angle % 360.0))
    return 

handle_theta_angle(-30)
handle_theta_angle(390)
handle_theta_angle(720)
handle_theta_angle(-720)
handle_theta_angle(-270)
handle_theta_angle(-30)



# def round_num_nearest_half(num, thresh_val):
#     #print(2*(round(num / thresh_val) * thresh_val))
#     print((2*(round(num / thresh_val) * thresh_val)))

# round_num_nearest_half(4.61, 0.5)
# round_num_nearest_half(3.2, 0.5)
# round_num_nearest_half(10.2, 0.5)



# print(2*(round_num_nearest_half(4.61, 0.5) / 0.5))

import matplotlib.pyplot as plt

# Define the starting and ending points of the arrow
x_start, y_start = 0, 0
x_end, y_end = 3, 3

# Create a figure and axis object
fig, ax = plt.subplots()

# Plot the arrow with a red tip and a blue body
ax.arrow(x_start, y_start, x_end-x_start, y_end-y_start,
         head_width=0.3, head_length=0.4, fc='red', ec='blue')

# Show the plot
plt.show()